---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default-dev
spec:
  encryptedData:
    DATABASE_URL: AgCWEVMtRcJk3cYH3WfNveKU/SqVuf6IPobVJUh++Mage37cb2Dr8LiUY0eE9W4QnEl9CwX1WUu0mxGje5QFYQ9pmBLQk8PK4dp5pSS0us8xh7+9b29mJ6VjSuSOI3AWhQYflPWvFhiXnEkHT8C4jziaY0nlgIRzutBa1KczfLsMRQMsdoFXbYwqgdgR+BhcuvBNJBxyTgFd2uxjKLQ3ltCtKqgvDBq2+fK+djgmIgIir2T8AxOfOjOTQZDl/XlJkcJtEOVzDr4aprjN2p/ZC1iuwYvfFg4HjYlrHSik3ExVZMtRIzjZy8+ECWVmofwtg3l+SBRWEzJFNcTwL/CGu71JcKkBID9SPAVqgH617COGLNebX7QYaePMBkryKI/GIdUzvFqPSrmD5aO1ykAgWa09Xso9jLK92T0i0z4JWSd9PiMN5JosS8a+c3EyTUS/KcyqopJBq+3XBcII7JddgJJ93cwD3nFtEvtVD9ir6RbbbF4PZi3DBWNFO4frUSgjKW6PBgLCtsFVYEAirfYuBZDYwJrhki5QDUkXnEDfNV+PUjQcYOKk2uXg3b5tZEzxYO5JJ4hI2o9lwWr+DfEqut6sNlQVebiHyqDtJDKKaV3iJKAOG+IuokP+NeGywlVQnZt71UYVLljm/X0a94xZ0HAmDx3G5nu2xXYvx1qca20vrIRiSbVUMudGLZuYCzl1pUMig1VYF4VKRpYr9H6MElfOIf2ST3GCanUIsa6i8w6PSwqG9+6ynaYlzWgEde7GQ2rVCXu5aLuxX3YQkK0Zw7omR9ZviQzZUWaqEE7sOni5v6NJA4v7sGW+Wh5V0ObJ
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default-dev
