apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-api-egress
  namespace: default-dev
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-cnpg
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.96.0.0/12
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 192.168.49.0/24
      ports:
        - protocol: TCP
          port: 8443
