apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-to-minio
  namespace: default-dev
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-cnpg
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
