apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: default-dev
data:
  backup-bucket: qoves-backups
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          ports:
            - containerPort: 9000
              name: s3
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default-dev
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      name: s3
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: default-dev
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin