apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"bitnami.com/v1alpha1","kind":"SealedSecret","metadata":{"annotations":{},"creationTimestamp":null,"name":"db-credentials","namespace":"default-dev"},"spec":{"encryptedData":{"DATABASE_URL":"AgCbP8WdJxax4NgU/FX2l++kY2mByEorGPeddeWuhrY7kAd39JwDA7RPaIQJ9L0LzcN0pazABT59xSa2/g95XACYUcQdYBYLYNIEq2Ox5kHTz55wcQb5xsJKAyf8HW3Oy+HwQDkyPgPE+yHxlxpM1ubaKUW4W0ww4PnBl+ZHZ0h4e9QicsPMNxpfG7T9OiNllP3Qs1QU7CrN0T3dvsv5ywUFmWNL6W4FXEm2wzaUSHAaQG47c2CoSNs1QzfGBcim3XApNkUiRip3zWzqN8NnTXXDJRNALYFNrbbIOsNiq1B3vAS5eebXdSGApxuadkK2dzF23XemL0SiKGGyvD24+lWsv9EzMdRavxBkBFqE2QVoh9vZmr2FhnJp6QJ5P3NXmCarpN0ptu+NaGpsAqa0TqxK4rKBnNzr598HrmreEYGGnaCYzdDdfKY5VbLj6cUedFQFlC/w7oS9dTal5QC/eaZpyEp6QYETuRDERETJszfp9gGJHXPylo9foRNHb+S2bfFhxAZvBIXNExV0KUGTQSs7Ojh2zr+dc1W0gGAeni6ZD4O9Ffvemy5AVpynZWO6TqUhf+h6kzRJD1Xbc8uZYIvVAjGmBARpxe7qip1zi+HuJWLJe1P1KQb4XoL/B+NKwMmhh7OXM10M9/5aYvGlMBHEtS4TgIKGm7YQaWtADMyEW9ewzutfBhpuGX4ult6bjFSb21nZQuk6pgStc96l+wlzYzjOARY5vskcbGVpEZ6fIAB/OpgOXmRpE2PhJ+E6K5iQPolNSYU7J8IKjdzNwdIB72dPsnqwhFUgEC+W9NKiVUAwVcuQOI+aI/3ALvyY"},"template":{"metadata":{"creationTimestamp":null,"name":"db-credentials","namespace":"default-dev"}}}}
  creationTimestamp: "2026-07-28T13:04:54Z"
  generation: 2
  name: db-credentials
  namespace: default-dev
  resourceVersion: "5000"
  uid: d7a540a8-7fce-49c0-96ba-7daa54ffd1f3
spec:
  encryptedData:
    DATABASE_URL: AgCbP8WdJxax4NgU/FX2l++kY2mByEorGPeddeWuhrY7kAd39JwDA7RPaIQJ9L0LzcN0pazABT59xSa2/g95XACYUcQdYBYLYNIEq2Ox5kHTz55wcQb5xsJKAyf8HW3Oy+HwQDkyPgPE+yHxlxpM1ubaKUW4W0ww4PnBl+ZHZ0h4e9QicsPMNxpfG7T9OiNllP3Qs1QU7CrN0T3dvsv5ywUFmWNL6W4FXEm2wzaUSHAaQG47c2CoSNs1QzfGBcim3XApNkUiRip3zWzqN8NnTXXDJRNALYFNrbbIOsNiq1B3vAS5eebXdSGApxuadkK2dzF23XemL0SiKGGyvD24+lWsv9EzMdRavxBkBFqE2QVoh9vZmr2FhnJp6QJ5P3NXmCarpN0ptu+NaGpsAqa0TqxK4rKBnNzr598HrmreEYGGnaCYzdDdfKY5VbLj6cUedFQFlC/w7oS9dTal5QC/eaZpyEp6QYETuRDERETJszfp9gGJHXPylo9foRNHb+S2bfFhxAZvBIXNExV0KUGTQSs7Ojh2zr+dc1W0gGAeni6ZD4O9Ffvemy5AVpynZWO6TqUhf+h6kzRJD1Xbc8uZYIvVAjGmBARpxe7qip1zi+HuJWLJe1P1KQb4XoL/B+NKwMmhh7OXM10M9/5aYvGlMBHEtS4TgIKGm7YQaWtADMyEW9ewzutfBhpuGX4ult6bjFSb21nZQuk6pgStc96l+wlzYzjOARY5vskcbGVpEZ6fIAB/OpgOXmRpE2PhJ+E6K5iQPolNSYU7J8IKjdzNwdIB72dPsnqwhFUgEC+W9NKiVUAwVcuQOI+aI/3ALvyY
  template:
    metadata:
      name: db-credentials
      namespace: default-dev
status:
  conditions:
  - lastTransitionTime: "2026-07-28T13:04:54Z"
    lastUpdateTime: "2026-07-28T13:13:16Z"
    status: "True"
    type: Synced
  observedGeneration: 2
