apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fencherr/home-task-1-minikube.git
    targetRevision: HEAD
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: default-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
